version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-secret-key-change-in-production
      - CORS_ORIGIN=*
      - LOG_LEVEL=info
      - NODE_ENV=production
    volumes:
      - .:/app
