name: CI

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup SQLite database
        run: |
          npx prisma generate
          npx prisma migrate deploy
          pnpm seed
        env:
          DATABASE_URL: "file:./test.db"
          JWT_SECRET: "test-secret-key"
          CORS_ORIGIN: "*"
          LOG_LEVEL: "error"
          NODE_ENV: "test"

      - name: Run linting
        run: pnpm lint

      - name: Run tests
        run: NODE_ENV=test pnpm test
        env:
          NODE_ENV: test
          DATABASE_URL: "file:./test.db"
          JWT_SECRET: "test-secret-key"
          CORS_ORIGIN: "*"
          LOG_LEVEL: "error"

      - name: Build application
        run: pnpm build

      - name: Build Docker image
        run: |
          docker build --no-cache -t ecommerce-backend .
        env:
          DOCKER_BUILDKIT: 1

      - name: Test Docker Compose
        run: docker-compose up -d --build
        env:
          DATABASE_URL: "file:./test.db"
